### ISSUE TITLE
Rust driver?

### ISSUE THREAD

**Issue by OfekShochat** [logicalclocks/irondb#102]
Hello! Rondb seems pretty cool!
When will there be a rust driver? I'd like to test rondb out in my current project

**Comment by mronstro** [comment]
You can access RonDB from a MySQL Server. There are Rust clients available to access MySQL.
There is also work ongoing to build a REST API towards RonDB. This will also make it possible
to access RonDB using Rust.

**Comment by OfekShochat** [comment]
ok, thank you so much and for the fast response! wasnt active lately..
