### ISSUE TITLE
Docker image / Docker-compose sample needed

### ISSUE THREAD

**Issue by jbenguira** [logicalclocks/irondb#49]
Hello, it would be great to have a docker version to allow everyone to test it quickly as we do with mysql for eg:
docker run --rm --name mysql-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mypassword -d mysql

**Comment by mronstro** [comment]
Started looking into it

**Comment by mronstro** [comment]
Blog post about Docker and RonDB: http://mikaelronstrom.blogspot.com/2021/08/rondb-and-docker.html
Documentation of Docker and RonDB: http://docs.rondb.com/rondb_docker
Any improvement ideas are welcome

**Comment by jbenguira** [comment]
Thanks a lot, this is super helpful!
A docker-compose that do everything in one step would be a great addition

**Comment by mronstro** [comment]
Will have a look, not so familiar currently with Docker Compose

**Comment by mronstro** [comment]
This docker-compose.yml almost works. For some reason the assignment of hostname on mysqld doesn't work, it gets IP 192.168.0.3 instead of the assigned 192.168.0.10:
version: "3.7"

volumes:
  mgm1-rondb:
  dn1-rondb:
  dn2-rondb:
  my1-rondb:

networks:
  default:
    external: true
    name: mynet

services:
  mgm1:
    image: mronstro/rondb:latest
    hostname: 192.168.0.2
    restart: always
    volumes:
      - mgm1-rondb:/var/lib/rondb
    command: [ "ndb_mgmd", "--ndb-nodeid=65", "--initial" ]
  dn1:
    image: mronstro/rondb:latest
    hostname: 192.168.0.4
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn1-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=1", "--initial" ]
  dn2:
    image: mronstro/rondb:latest
    hostname: 192.168.0.5
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn2-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=2", "--initial" ]
  my1:
    image: mronstro/rondb:latest
    hostname: 192.168.0.10
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    depends_on:
      - mgm1
      - dn1
      - dn2
    volumes:
      - my1-rondb:/var/lib/mysql
    command: [ "mysqld", "--ndb-cluster-connection-pool-nodeids=67" ]

**Comment by mronstro** [comment]
This docker-compose.yml worked just fine, it uses the external network mynet
that I defined with the command:
docker network create mynet --subnet=192.168.0.0/16
Thus one could connect to the MySQL Server using mynet on IP 192.168.0.10 after
starting the cluster:
version: "3.7"

volumes:
  mgm1-rondb:
  dn1-rondb:
  dn2-rondb:
  my1-rondb:

networks:
  mynet:
    external: true

services:
  mgm1:
    image: mronstro/rondb:latest
    networks:
      mynet:
        ipv4_address: 192.168.0.2
    restart: always
    volumes:
      - mgm1-rondb:/var/lib/rondb
    command: [ "ndb_mgmd", "--ndb-nodeid=65", "--initial" ]
  dn1:
    image: mronstro/rondb:latest
    networks:
      mynet:
        ipv4_address: 192.168.0.4
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn1-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=1", "--initial" ]
  dn2:
    image: mronstro/rondb:latest
    networks:
      mynet:
        ipv4_address: 192.168.0.5
    restart: always
    depends_on:
      - mgm1
    volumes:
      - dn2-rondb:/var/lib/rondb
    command: [ "ndbmtd", "--ndb-nodeid=2", "--initial" ]
  my1:
    image: mronstro/rondb:latest
    networks:
      mynet:
        ipv4_address: 192.168.0.10
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    depends_on:
      - mgm1
      - dn1
      - dn2
    volumes:
      - my1-rondb:/var/lib/mysql
    command: [ "mysqld", "--ndb-cluster-connection-pool-nodeids=67" ]

**Comment by mronstro** [comment]
http://mikaelronstrom.blogspot.com/2021/08/rondb-and-docker-compose.html
