### ISSUE TITLE
Rondb scalability? 

### ISSUE THREAD

**Issue by cih-y2k** [logicalclocks/irondb#65]
I cannot find the details about Rondb in its documents. If I don’t remember wrong, I’ve read in the “MySQL Cluster 7.5 inside and out” book, NDB data node cluster can scale up to 48 nodes, but the message address size is 16 bit. Can you guys give me some more details about this?

I also created a topic here: https://community.rondb.com/t/rondb-scalability/18

**Comment by mronstro** [comment]
As mentioned on the community question RonDB scales to 144 data nodes with a maximum of 255 nodes in total.
On the TODO list is to mainly extend the total number of nodes in the cluster beyond 255. The address size enables
RonDB to scale to 65536 nodes, but probably we'll go for something like 2k or 8k nodes as a starter.
